name: Docker Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub (Optional - if you need to pull private base images or push images)
        # uses: docker/login-action@v2
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "Skipping Docker Hub login for now." # Placeholder if not immediately needed

      - name: Build services with docker-compose
        run: docker-compose build
        # The command `docker-compose build` will build all services defined in docker-compose.yml
        # This implicitly tests if all Dockerfiles are correct and dependencies can be installed.

      # Optional: Add steps here to run tests within the containers,
      # push images to a registry, or deploy.

      # Example: Lint Dockerfiles (Optional)
      # - name: Lint Dockerfiles
      #   uses: hadolint/hadolint-action@v3.1.0
      #   with:
      #     dockerfile: |
      #       ./py.Dockerfile
      #       ./node.Dockerfile
      #       ./db.Dockerfile
      #       ./caddy.Dockerfile

      - name: Echo completion message
        run: echo "Docker images built successfully (or build process tested)."
